Feat/gp/init harvest admin
Informasjonsforvaltning/concept-catalogue pull request #122
Opened 2019-11-06 14:07 UTC by Chlenix

2019-11-06 15:00 UTC, azaxarov requested changes

2019-11-06 15:00 UTC, azaxarov commented on src/main/java/no/brreg/conceptcatalogue/service/ConceptPublisher.java
> +        payload.put("description", "beskrivelse");
Description can be something slightly more meaningful, i.e. "Automatically generated data source for ${publisherId}"

2019-11-06 15:00 UTC, azaxarov commented on src/main/kotlin/no/brreg/conceptcatalogue/BegreperApiImplK.kt
> +        var newBegrep: Begrep = begrep
newBegrep is never reassigned, so can remain a val

2019-11-06 15:00 UTC, azaxarov commented on src/main/kotlin/no/brreg/conceptcatalogue/BegreperApiImplK.kt
> +        // add entry in harvest admin if no concepts existed previously
Convert this rather to a log entry

2019-11-06 15:00 UTC, azaxarov commented on src/main/kotlin/no/brreg/conceptcatalogue/BegreperApiImplK.kt
> +                .build()
Can call toUriString immediately instead of next line

2019-11-06 15:00 UTC, azaxarov commented on src/main/kotlin/no/brreg/conceptcatalogue/BegreperApiImplK.kt
> +    override fun setBegrepById(httpServletRequest: HttpServletRequest?, id: String, jsonPatchOperations: List<JsonPatchOperation>?, validate: Boolean?): ResponseEntity<Begrep> {
Is it correct according to the spec that id is mandatory?

2019-11-06 15:00 UTC, azaxarov commented on src/main/kotlin/no/brreg/conceptcatalogue/BegreperApiImplK.kt
> +            if (patchedBegrep.status == Status.PUBLISERT || storedBegrep.status == Status.PUBLISERT) {
or condition seems unnecessary

2019-11-06 15:08 UTC, markkopaas requested changes
du har et par små fixup commit, som kan squashes , til ungå original feil.

2019-11-06 15:08 UTC, markkopaas commented on src/main/java/no/brreg/conceptcatalogue/service/ConceptPublisher.java
> +            payload.put("publisherId", publisherId);
i drømme,  kunne det være knuttet til modell i spec på en eller en ant måte. bare tenk om det.

2019-11-06 15:08 UTC, markkopaas commented on src/main/kotlin/no/brreg/conceptcatalogue/BegreperApiImplK.kt
> +        val begreperTilVirksomhet = begrepRepository.getBegrepByAnsvarligVirksomhetId(begrep.ansvarligVirksomhet.id)
vi trenger å spørre bare antall fra repository, ikke laste ned alt data. Jeg tror repository interface har den generator., hvis ikke, da kan du håndlage en mongotemplate query

2019-11-06 15:08 UTC, markkopaas commented on src/test/kotlin/ControllerTest.kt
> +        val baseUrl = "https://registrering-begrep.ut1.fellesdatakatalog.brreg.no"
i unit test, du kan bruke mer test-like innehold. "testurl", for eksempel

2019-11-06 15:08 UTC, markkopaas commented on src/main/java/no/brreg/conceptcatalogue/service/ConceptPublisher.java
> +        ObjectNode payload = JsonNodeFactory.instance.objectNode();
du har en enkelt fixup av kommit du nettop legg til... anbefaler å squashe de to commit

2019-11-06 15:08 UTC, markkopaas commented on src/main/java/no/brreg/conceptcatalogue/service/ConceptPublisher.java
> +        payload.put("dataSourceType", "SKOS-AP-NO");
igjen, fixup av feil. du jar em sjansje å iikke gjøre den feil - squashe med commit

2019-11-06 15:08 UTC, markkopaas commented on src/main/kotlin/no/brreg/conceptcatalogue/BegreperApiImplK.kt
> -        if (id == null) {
hvis en feature PR tar lang tid i review, da kan du gjøre det litt raskere, hvis du har en ant PR på side, som inneholder bare de små helt urelatere ting-tang

2019-11-06 15:08 UTC, markkopaas commented on src/main/kotlin/no/brreg/conceptcatalogue/BegreperApiImplK.kt
> +    override fun setBegrepById(httpServletRequest: HttpServletRequest?, id: String, jsonPatchOperations: List<JsonPatchOperation>?, validate: Boolean?): ResponseEntity<Begrep> {
det path variable... så hvis det kompilerer, da er det riktig... router matcher ikke controller med null path variable

2019-11-06 15:08 UTC, markkopaas commented on src/main/kotlin/no/brreg/conceptcatalogue/BegreperApiImplK.kt
> +            if (patchedBegrep.status == Status.PUBLISERT || storedBegrep.status == Status.PUBLISERT) {
haha, les igjen 😄

2019-11-08 14:32 UTC, Chlenix commented on src/main/java/no/brreg/conceptcatalogue/service/ConceptPublisher.java
> +        payload.put("description", "beskrivelse");
fixed

2019-11-11 09:39 UTC, azaxarov approved these changes

2019-11-11 11:54 UTC, markkopaas requested changes

2019-11-11 11:54 UTC, markkopaas commented on src/main/kotlin/no/brreg/conceptcatalogue/BegreperApiImplK.kt
> +        val begreperTilVirksomhet = begrepRepository.getBegrepByAnsvarligVirksomhetId(begrep.ansvarligVirksomhet.id)
kan vi holde oss med absolutt minimal norsk. Den eneste sted vi har norsk er begrepmodellfelter. Trenger variabler i norsk

2019-11-11 11:54 UTC, markkopaas commented on src/main/kotlin/no/brreg/conceptcatalogue/BegreperApiImplK.kt
> +    override fun setBegrepById(httpServletRequest: HttpServletRequest?, id: String, jsonPatchOperations: List<JsonPatchOperation>?, validate: Boolean?): ResponseEntity<Begrep> {
den endring behover til den forrige commit

2019-11-11 11:54 UTC, markkopaas commented on src/main/resources/static/ConceptRegistrationAPI.yaml
> +    DataSource:
jeg tror ikke at det er riktig å eksponere modell, hvis det er ikke i bruk i noen av de endepunktene. Du kan uanset registrere  domain object class i din kode, trenger ikke å ha det generert fra spec

2019-11-11 11:54 UTC, markkopaas commented on src/main/kotlin/no/brreg/conceptcatalogue/BegreperApiImplK.kt
> +        val begreperTilVirksomhet = begrepRepository.countBegrepByAnsvarligVirksomhetId(begrep.ansvarligVirksomhet.id)
ikke bruke norsk, kanskje begrepCount

2019-11-11 11:54 UTC, markkopaas commented on src/main/kotlin/no/brreg/conceptcatalogue/BegreperApiImplK.kt
> +        val begreperTilVirksomhet = begrepRepository.countBegrepByAnsvarligVirksomhetId(begrep.ansvarligVirksomhet.id)
her fikser du en problem som du har tidligere generert. så det er dobbelt så mye o review (og teste!). sterkt anbefalt å squashe den commit med den originalkommit, så det er mindre endringer

2019-11-11 11:54 UTC, markkopaas commented on src/main/kotlin/no/brreg/conceptcatalogue/BegreperApiImplK.kt
> +        if (begreperTilVirksomhet == 0L) {
variablenavn fortsett refererer til kolleksjon.

2019-11-11 13:35 UTC, markkopaas approved these changes

2019-11-11 13:35 UTC, markkopaas commented on src/main/java/no/brreg/conceptcatalogue/model/DataSource.java
> +@JsonIgnoreProperties(ignoreUnknown = true)
ved hjelp av @lombok blir det class ~4 linje :)

2019-11-11 13:58 UTC, merged