fix: #99 added brukerId to endringslog
Informasjonsforvaltning/concept-catalogue pull request #123
Opened 2019-11-11 11:52 UTC by Chlenix

2019-11-11 11:53 UTC, Chlenix commented
Denne må vente litt til vi har fått svar på om det er OK å lagre personnr. mtp. GDPR

2019-11-11 12:29 UTC, markkopaas requested changes

2019-11-11 12:29 UTC, markkopaas commented on src/main/java/no/brreg/conceptcatalogue/service/permission/PermissionService.java
> +    public String getBrukerId() {
ikke bruke norsk i kode. det er mer enn nokk at begrepmodell er i norsk. UserId

2019-11-11 14:24 UTC, markkopaas approved these changes

2019-11-12 11:10 UTC, azaxarov approved these changes

2019-11-13 11:13 UTC, merged