Refactor/az/harvest controller refactoring
Informasjonsforvaltning/concept-catalogue pull request #126
Opened 2019-11-12 14:10 UTC by azaxarov

2019-11-12 14:21 UTC, azaxarov commented
I will need to add COLLECTION_BASE_URI to fdk-config before merging this branch

2019-11-13 09:28 UTC, markkopaas requested changes
PR var lett lesbar takk til separarerte og selvstendige committene. Takk!

2019-11-13 09:28 UTC, markkopaas commented on src/main/kotlin/no/brreg/conceptcatalogue/service/ConceptService.kt
> +    fun getPublisherIds(): List<String> {
anbefaler getAllPublisherIds

2019-11-13 09:28 UTC, markkopaas commented on src/main/kotlin/no/brreg/conceptcatalogue/service/ConceptService.kt
> +    fun getConceptsForPublisherId(publisherId: String, status: Status): List<Begrep> {
vurdere privat, det er litt kompleks interface og du egentlig vill ikke ha direkte ekstene kall.

ha ingen eller full parameter list i navn - getConceptsForPublisherIdAndStatis

2019-11-13 09:28 UTC, markkopaas commented on src/main/kotlin/no/brreg/conceptcatalogue/service/ConceptService.kt
> +    fun getPublishedConceptsForPublisherId(publisherId: String): List<Begrep> {
vurdere bruke "find" i stedet av "get", når du gjør søk, i stedet av forventent svar som du kan "ta". Ja du har plural "concepts" men det hjelper litt å vise intensjon.

2019-11-13 09:28 UTC, markkopaas commented on src/main/resources/application.yml
> +  collectionBaseUri: ${COLLECTION_BASE_URI}
den ser  ut at behover i den neste commit

2019-11-13 09:28 UTC, markkopaas commented on src/main/kotlin/no/brreg/conceptcatalogue/HarvestEndpoint.kt
> +    @Value("\${application.collectionBaseUri}")
Heg forstår ikke helt. 
Hvis du trenger en nytt konfigurasjonvariable, da må det være noe helt galt og det er produksjonsbug eller?
Hvis du trenger å separeri internt logikk, da kan du minst ha reasobable defaulting så at man trenger ikke nye eksterne variabler og konfigurasjonskostnad.

Vi ønsker å minimisere sjanser at system ble feilkonfigurert -> minimal antall av variabler.

2019-11-13 09:28 UTC, markkopaas commented on src/main/kotlin/no/brreg/conceptcatalogue/service/SkosApNoModelBuilderService.kt
> +class SkosApNoModelBuilderService(
kan  ikke model builder og serializer leve sammen i SkosApiNoModelService? akkurat som du har ConceptService?

2019-11-13 09:28 UTC, markkopaas commented on src/test/kotlin/no/brreg/conceptcatalogue/service/SkosApNoModelSerialiserServiceTest.kt
> +class SkosApNoModelSerialiserServiceTest() {
serialiser er ikke vår funksjon, så vi burde ikke å teste det (mye). kanskje en suksee og en feil case. 

men den ekte test må være modelbuilder. det ser ut til meg ag stor del av de testene her kan bare flyttes til modelbuilder tests, bare at do kan fjerne serializer-deserializer steg.

2019-11-13 12:31 UTC, azaxarov commented on src/main/kotlin/no/brreg/conceptcatalogue/service/ConceptService.kt
> +    fun getPublisherIds(): List<String> {
fixed

2019-11-13 12:31 UTC, azaxarov commented on src/main/kotlin/no/brreg/conceptcatalogue/service/ConceptService.kt
> +    fun getConceptsForPublisherId(publisherId: String, status: Status): List<Begrep> {
fixed

2019-11-13 12:32 UTC, azaxarov commented on src/main/resources/application.yml
> +  collectionBaseUri: ${COLLECTION_BASE_URI}
fixed

2019-11-13 12:32 UTC, azaxarov commented on src/main/kotlin/no/brreg/conceptcatalogue/HarvestEndpoint.kt
> +    @Value("\${application.collectionBaseUri}")
fixed

2019-11-13 12:32 UTC, azaxarov commented on src/main/kotlin/no/brreg/conceptcatalogue/service/SkosApNoModelBuilderService.kt
> +class SkosApNoModelBuilderService(
fixed

2019-11-13 12:32 UTC, azaxarov commented on src/test/kotlin/no/brreg/conceptcatalogue/service/SkosApNoModelSerialiserServiceTest.kt
> +class SkosApNoModelSerialiserServiceTest() {
fixed

2019-11-13 12:49 UTC, markkopaas commented on src/main/kotlin/no/brreg/conceptcatalogue/HarvestEndpoint.kt
> +        return ResponseEntity.ok(skosApNoModelService.serializeAsTextTurtle(when {
jeg synes tre linjer var bedre - model, text, response.

2019-11-13 12:53 UTC, markkopaas approved these changes

2019-11-13 12:57 UTC, merged