feat(concept-client): #1846 add Header
Informasjonsforvaltning/concept-catalogue pull request #19
Opened 2019-06-05 13:20 UTC by skobba

2019-06-05 17:43 UTC, oyvindis commented on concept-client/src/components/app-header/app-header.component.tsx
> +        <a id="skip-link" href={`${location.pathname}#content`} />
Her må det være noe tekst mellom <a ...>Hopp til hovedinnhold</a> slik at denne linken blir synlig når man bruker tab når man lander på siden.

2019-06-05 17:49 UTC, oyvindis commented on concept-client/src/components/app-header/app-header.component.tsx
> +  let headerTitle = localization['title'];
'title' - siden språkfil må være flat så tror jeg det er lurt om vi angir med key som sier noe om komponent i starten av key, f.eks. at du endrer denne til 'headerTitle'.

Så har vi andre helt generelle ord som vi kan anta skal brukes flere steder og de trenger ikke prefix, f.eks. 'createNew' er et ord som antas å brukes flere steder.

2019-06-05 17:50 UTC, oyvindis commented on concept-client/src/components/app-header/app-header.component.tsx
> +                <img className="fdk-logo" src="./img/logo-registrering.svg" alt="Logo for Felles datakatalog" />
Gjorde du designreview med Lene? Skal logoen være så liten?

2019-06-05 17:51 UTC, oyvindis requested changes
Bra, har bare et par kommentarer.

2019-06-06 06:21 UTC, skobba commented on concept-client/src/components/app-header/app-header.component.tsx
> +        <a id="skip-link" href={`${location.pathname}#content`} />
Endret

2019-06-06 06:24 UTC, skobba commented on concept-client/src/components/app-header/app-header.component.tsx
> +  let headerTitle = localization['title'];
Venter med dette

2019-06-06 06:51 UTC, oyvindis approved these changes

2019-06-06 06:51 UTC, merged