The liquibase sql now contains various fixes to make it run on GCE.
Informasjonsforvaltning/concept-catalogue pull request #32
Opened 2019-06-21 05:50 UTC by thomasnokleby

2019-06-21 12:07 UTC, markkopaas requested changes

2019-06-21 12:07 UTC, markkopaas commented on applications/concept-catalogue/src/main/kotlin/no/begrepskatalog/conceptregistration/BegreperApiImplK.kt
>      override fun getBegrep(httpServletRequest: HttpServletRequest?, @PathVariable orgnumber: String?, status: Status?): ResponseEntity<MutableList<Begrep>> {
hva er meningen av dette endring?

2019-06-21 12:07 UTC, markkopaas commented on applications/concept-catalogue/src/main/kotlin/no/begrepskatalog/conceptregistration/BegreperApiImplK.kt
> +
støy

2019-06-21 12:07 UTC, markkopaas commented on applications/concept-catalogue/src/main/kotlin/no/begrepskatalog/conceptregistration/storage/SqlStore.kt
> +            if (thisVirksomhet != null) {}
blokken er tomt

2019-06-21 12:07 UTC, markkopaas commented on applications/concept-catalogue/src/main/resources/liquibase/changelog/changelog-1.0.xml
> +           <column name="org_number" type="TEXT">
det er veldig ofte, at changelog kan ikke endres. er du absolutt sikkert at dette hhar ikke kjørt i ikke noe miljø?

2019-06-21 12:07 UTC, thomasnokleby commented on applications/concept-catalogue/src/main/resources/liquibase/changelog/changelog-1.0.xml
> +           <column name="org_number" type="TEXT">
Det er jeg :)

2019-06-22 13:47 UTC, thomasnokleby commented on applications/concept-catalogue/src/main/kotlin/no/begrepskatalog/conceptregistration/BegreperApiImplK.kt
>      override fun getBegrep(httpServletRequest: HttpServletRequest?, @PathVariable orgnumber: String?, status: Status?): ResponseEntity<MutableList<Begrep>> {
Dette var en bug. Hele kontrolleren implementerer et interface, som også innehar Mapping-Annoteringer. Når denne fjernes så brukes interfacet sin mapping.

2019-06-22 13:54 UTC, thomasnokleby commented on applications/concept-catalogue/src/main/kotlin/no/begrepskatalog/conceptregistration/BegreperApiImplK.kt
> +
fixed

2019-06-22 13:54 UTC, thomasnokleby commented on applications/concept-catalogue/src/main/kotlin/no/begrepskatalog/conceptregistration/storage/SqlStore.kt
> +            if (thisVirksomhet != null) {}
fixed

2019-06-22 14:07 UTC, merged