feat(concept-catalogue): #1848 add validation to publishable concepts
Informasjonsforvaltning/concept-catalogue pull request #55
Opened 2019-08-12 09:58 UTC by azaxarov

2019-08-12 10:13 UTC, thomasnokleby commented on applications/concept-catalogue/src/main/kotlin/no/begrepskatalog/conceptregistration/validation/BegrepValidator.kt
> +
Er ikke dette funksjonelt likt med 
if (begrep.status==null )return false
if (begrep.status == Status.UTKAST) return false 
?

2019-08-12 10:17 UTC, NilsOveTen commented on applications/concept-catalogue/src/main/kotlin/no/begrepskatalog/conceptregistration/BegreperApiImplK.kt
> +    private fun validatePublishableBegrep(begrep: Begrep): Boolean {
Er det ikke like så greit å fjerne denne metoden, og bruke BegrepValidator.validate() direkte? Dvs "validatePublishableBegrep(updatedBegrep)" -> "BegrepValidator.validate(updatedBegrep)" på linje 82

2019-08-12 10:17 UTC, NilsOveTen commented on applications/concept-catalogue/src/main/kotlin/no/begrepskatalog/conceptregistration/validation/BegrepValidator.kt
> +class BegrepValidator {
Du kan dra hele validate metoden ut av klassen, virker unødvendig å ha en klasse bare for companion object

2019-08-12 10:17 UTC, NilsOveTen commented on applications/concept-catalogue/src/main/kotlin/no/begrepskatalog/conceptregistration/validation/BegrepValidator.kt
> +            begrep.status?.let {
Tipper du kan samle alle de forskjellige let funkssjonene i en when

2019-08-12 10:19 UTC, NilsOveTen commented on applications/concept-catalogue/src/main/kotlin/no/begrepskatalog/conceptregistration/validation/BegrepValidator.kt
> +
jepp, det ser sånn ut

2019-08-12 10:38 UTC, thomasnokleby commented on applications/concept-catalogue/src/main/kotlin/no/begrepskatalog/conceptregistration/validation/BegrepValidator.kt
> +
Hør med Nils Ove hva som er beste syntax her :)

2019-08-12 10:41 UTC, thomasnokleby commented on applications/concept-catalogue/src/test/kotlin/ConceptRegistrationApplicationTest.kt
> +    fun testBegrepAnbefaltTermValidation() {
Jeg antar her at anbefalt term skal ha en verdi. Et bedre navn for testen er noe slikt som testValidateAnbefaltTermNonNull eller MustHaveValue.

2019-08-12 10:42 UTC, thomasnokleby commented on applications/concept-catalogue/src/test/kotlin/ConceptRegistrationApplicationTest.kt
> +    fun testBegrepDefinisjonValidation() {
Som anbefalt term

2019-08-12 10:45 UTC, azaxarov commented on applications/concept-catalogue/src/main/kotlin/no/begrepskatalog/conceptregistration/BegreperApiImplK.kt
> +    private fun validatePublishableBegrep(begrep: Begrep): Boolean {
Enig

2019-08-12 10:49 UTC, thomasnokleby commented on applications/concept-catalogue/src/test/kotlin/ConceptRegistrationApplicationTest.kt
> +    fun testBegrepKildebeskrivelseValidation() {
som anbefalt term

2019-08-12 10:49 UTC, thomasnokleby commented on applications/concept-catalogue/src/test/kotlin/ConceptRegistrationApplicationTest.kt
> +        val validator = { b: Begrep -> BegrepValidator.validate(b) }
som anbefalt term

2019-08-12 10:51 UTC, thomasnokleby commented on applications/concept-catalogue/src/test/kotlin/ConceptRegistrationApplicationTest.kt
> +        val validator = { b: Begrep -> BegrepValidator.validate(b) }
(bare spørsmål for avklaring).
Her er regelen at fagområde KAN være null, men om det ikke er det så skal det være en streng ?

2019-08-12 10:57 UTC, thomasnokleby requested changes
Mye bra, men tror kotlinsyntaxen kan bli bedre

2019-08-13 08:10 UTC, NilsOveTen commented on applications/concept-catalogue/src/main/kotlin/no/begrepskatalog/conceptregistration/validation/BegrepValidator.kt
> +    begrep.anbefaltTerm == null -> false
Kan potensielt bruke "isNullOrBlank()" for å slå sammen linjene som sjekker null og blank på samme verdi

2019-08-13 08:16 UTC, NilsOveTen approved these changes

2019-08-13 08:16 UTC, NilsOveTen commented on applications/concept-catalogue/src/main/kotlin/no/begrepskatalog/conceptregistration/validation/BegrepValidator.kt
> +    val digits: List<Int> = organisationNumber.dropLast(1).split("").filter { !it.isBlank() }.map { it.toInt() }
Vil si det blir enklere å lese om du har hver av de forskjellige funksjonene på en ny linje

val digits: List<Int> = organisationNumber
    .dropLast(1)
    .split("")
    .filter { !it.isBlank() }
    .map { it.toInt() }

2019-08-13 08:25 UTC, thomasnokleby commented on applications/concept-catalogue/src/main/kotlin/no/begrepskatalog/conceptregistration/validation/BegrepValidator.kt
> +
Dette ble mye mer kompakt, OG leselig 👍

2019-08-13 08:28 UTC, thomasnokleby commented on applications/concept-catalogue/src/main/kotlin/no/begrepskatalog/conceptregistration/validation/BegrepValidator.kt
> +    return organisationNumber == "${digits.joinToString("")}${ModUtil.calculateMod11Check(digits, 7)}"
Hva gjør denne linjen, egentlig ? 
Ser du konverterer intene som er sifferne tilbake til en string, men så detter jeg av

2019-08-13 08:29 UTC, thomasnokleby approved these changes
Mye bedre, men kan du se om du kan gjøre den ene kommenterte linjen lettere å lese ?

2019-08-13 10:08 UTC, merged